import { createElement } from 'lwc';
import RMS_Child_Custom_Lookup from 'c/rMS_Child_Custom_Lookup';

describe('c-r-m-s-child-custom-lookup', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-r-m-s-child-custom-lookup', {
            is: RMS_Child_Custom_Lookup
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});